### ISSUE TITLE
how to deploy scheduler extender

### ISSUE THREAD

**Issue by tommenx** [Huang-Wei/sample-scheduler-extender#1]
thank you to give a demo about how to make my own scheduler extender. And I want to know how to deploy it. Does it need to modify the kube-apiserver deployment yaml file and redeploy it?

**Comment by Huang-Wei** [comment]
Nope, only scheduler is involved.

## if you can control where/how scheduler is deployed

The only piece to tweak is the scheduler startup parameters. Make sure to provide an scheduler policy file https://github.com/Huang-Wei/sample-scheduler-extender/blob/047fdd5ae8b1a6d7fdc0e6d20ce4d70a1d6e7178/manifests/hack-local/scheduler-extender-config.yaml#L8, and the policy file should be able to specify the extender webhook URL, as well as other info: https://github.com/Huang-Wei/sample-scheduler-extender/blob/047fdd5ae8b1a6d7fdc0e6d20ce4d70a1d6e7178/manifests/hack-local/scheduler-extender-policy.json#L1-L11

## if you can't control where/how scheduler is deployed

Which means you can't directly change startup parameters of the default scheduler. In this caes, a workaround is to run a "duplicate" copy of default scheduler as a Pod, and register it as a new name (e.g. "your-scheduler"), and provide the scheduler policy file to it. And to ensure your pod is scheduled by "your-scheduler", the testing pod yaml should specify "sepc.schedulerName = <your-scheduler>".

(this trick is sort of known as "multi-schedulers", you can google for details)

**Comment by tommenx** [comment]
Thank you very much for your answer, your project has helped me a lot.
I have no other questions, and I will close it later.

**Comment by darcyllingyan** [comment]
Hi @Huang-Wei , @tommenx,
I have a question.
In one deployed cluster, now I have run a "duplicate" copy of default scheduler as a Pod, and register it as a new name, i.e., multi-schedulers.
Now I want to merge the default scheduler and the scheduler extender, want to confirm whether only change below two places of the default scheduler POD yaml file?
 
1. Modify the scheduler POD yaml, add  new option **--config=/etc/kubernetes/sched-config-v1alpha1.yaml**, in the yaml file pass-in the extender policy :
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --config=/etc/kubernetes/sched-config-v1alpha1.yaml
```
2. I have built the scheduler extender as a docker image **extender:v1.0** (the code including predicates.go, routes.go ...), how did I merge the extender image to the default scheduler? Need I just add the container kube-scheduler-plugin to default scheduler POD yaml file?

extender:v1.0
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
containers:
- name: kube-scheduler
  image: "{{ kube_scheduler_image }}:{{ kube_version }}"
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --config=/etc/kubernetes/sched-config-v1alpha1.yaml
 

- name:  kube-scheduler-plugin
        image: extender:v1.0
        ports:
        - containerPort: 8888
  
   ...


```
After change the above two places, the extender will be worked together with default scheduler, right?
Thanks for your response.

**Comment by Huang-Wei** [comment]
@darcyllingyan Are you running on a managed k8s offering? i.e., do you have access to the control plane?

**Comment by darcyllingyan** [comment]
Hi @Huang-Wei,
Yes, I have access to the control plane.

**Comment by darcyllingyan** [comment]
Hi @Huang-Wei ,
I have another question. I modified the urlPrefix and add 8033 port to it.  But in the kube-scheduler logs, it doesn't work and still searching 80 port, do you have any suggestions? Thanks.
```
scheduler.go:599] error selecting node for pod: Post http://localhost/scheduler/predicates/always_true: dial tcp [::1]:80: connect: connection refused
```
```
"extenders" : [{
        "urlPrefix": "http://localhost:8033/scheduler",
        "filterVerb": "predicates/always_true",
        "prioritizeVerb": "priorities/zero_score",
```

**Comment by Huang-Wei** [comment]
Did you restart scheduler to ensure the new config is effective?

**Comment by darcyllingyan** [comment]
Thanks @Huang-Wei ,
In kubernetes v1.18, I have started the extender successfully.
But after I upgrade the kubernetes from v1.18 to v1.19, the kubeschedulerConfiguration structure is changed.
In the config.yaml, the algorithmSource is removed, and the format is changed to:
```
profiles:
  - schedulerName: 'default-scheduler'
    pluginConfig:
      - name: 'InterPodAffinity'
      - args:
          hadPodAffinityWeight: <value>
```
So I'm not sure how this bind to the policy.cfg? How it triggers the scheduler extender?  Thanks very much for any response.
