### ISSUE TITLE
How to apply this schedule extender to kind Kubernetes cluster

### ISSUE THREAD

**Issue by srini1978** [Huang-Wei/sample-scheduler-extender#5]
Hi,
I am running a Kubernetes cluster using kind. To apply the schedule extender policy.json i need to apply this to kube-scheduler . however i am getting a kube-scheduler: command not found

I am trying to use the same extender logic for kube-scheduler. How will "kind" be able to work with this scheduler and customize it ?
Any pointers?

**Comment by Huang-Wei** [comment]
With `kind`, you may need to tweak the kube-scheduler startup arguments to pass-in the policy.{json|yaml}.

The first step is to craft the static scheduler Pod yaml to replace the default one inside container `kind-control-plane`. e.g.,

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --config=/etc/kubernetes/sched-config-v1alpha1.yaml
    # - --kubeconfig=/etc/kubernetes/scheduler.conf
    # - --leader-elect=true
......
```

And then in `/etc/kubernetes/sched-config-v1alpha1.yaml`, pass-in the extender policy via `File` or `ConfigMap`.

Hope this helps.
