### ISSUE TITLE
How the scheduler extender used in Kubernetes v1.19

### ISSUE THREAD

**Issue by darcyllingyan** [Huang-Wei/sample-scheduler-extender#7]
Hi @Huang-Wei  ,
In kubernetes v1.18, I have started the extender successfully.
But after I upgrade the kubernetes from v1.18 to v1.19, the kubeschedulerConfiguration structure is changed.
In the config.yaml, the algorithmSource is removed, and the format is changed to:
```
profiles:
  - schedulerName: 'default-scheduler'
    pluginConfig:
      - name: 'InterPodAffinity'
      - args:
          hadPodAffinityWeight: <value>
```
So I'm not sure how this bind to the policy.cfg? How it triggers the scheduler extender? Thanks very much for any response.

**Comment by Huang-Wei** [comment]
@darcyllingyan you can compose the config yaml like this:

```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "PATH_OF_KUBE_CONFIG"
# Provide profiles if you want to customize the default plugins of profile `default-scheduler`
# or compose new profiles.
profiles:
......
# Extenders are registered to all profiles
extenders:
- urlPrefix: ...
  filterVerb: ...
```
